### ISSUE TITLE
How to join the slack?

### ISSUE THREAD

**Issue by wdimmy** [patrik999/stream-reasoning-challenge#2]
When I click the link, it always said that "wangdimmy@gmail.com doesn’t have an account on this workspace"

**Comment by patrik999** [comment]
Hey Dingmin, I have added you to Slack workspace, feel free to ask questions there.

**Comment by manosntoulias** [comment]
Hello can you add me as well?

**Comment by patrik999** [comment]
Only relevant for Hackathon
